### PR TITLE
Fix nativeswap and staking test

### PR DESCRIPTION
**Pull request by GeertWille**

### CODE REVIEW

**Comment by sigurdpl** [comment]
Well its big ! So many changes made to the smart contracts argument lists without the unittests reflecting this. Well I am going with gut feeling here and like to approve this, we are running out of time. For me its thumbs up

**Comment by sigurdpl** [comment]
Ahh, I checked, two of the staking tests not passing. Ok i will try to get on with it

**Review by Vicarious1 — APPROVED** [review]
Changes looks sound to me! Thanks!

**Comment by Vicarious1** [comment]
Merging because @sigurdpl is going to be working on the staking test today

**Pull request merged**
