### PR TITLE
change average price to 3 days (variable)

### PR DESCRIPTION
**Pull request by petec86**

### CODE REVIEW

**Review by Dellybro — CHANGES_REQUESTED** [review]
this should be controlled variably. imo, so we don't have to keep updating the contract rather just call a tx to update a single value

**Comment by petec86** [comment]
> this should be controlled variably. imo, so we don't have to keep updating the contract rather just call a tx to update a single value

done.

**Review by Mvii7 — APPROVED** [review]
This'll do without tests

**Comment by Mvii7** [comment]
there should be a test to at least check the set works

**Review by Dellybro — APPROVED** [review]

**Pull request merged**
